name: Author-Service-CI

on:
  push:
    paths:
      - "services/author/**"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      
      - name: Setup Node.js 
        uses: actions/setup-node@v4 
        with:
          node-version: 22
          cache: npm 

      - name: Install Dependencies 
        working-directory: services/author
        run: npm ci 
      
      - name: Build Project
        working-directory: services/author
        run: |
          npm run build
      
      - name: Run Tests
        working-directory: services/author
        run: |
          npm start &
            sleep 5

      - name: Health check endpoints 
        run: |
          curl -f http://localhost:5001/try

  cd-build:
    permissions:
      id-token: write 
      contents: read 
    needs: ci 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4 

      - name: Set Up Docker 
        uses: docker/setup-buildx-action@v3 

      - name: Debug Docker context
        run: |
          pwd
          ls
          ls services 
          ls services/author 

      - name: Build Docker Image 
        working-directory: ./services/author
        run: |
          docker build -t author-service:ci-test .

      - name: Configure AWS 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: eu-north-1

      - name: Login to ECR
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Docker Image
        working-directory: services/author 
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          IMAGE=${{github.sha}}
          ECR_REPO=author-service 
          docker build -t $ECR_REPO:IMAGE .
          docker tag $ECR_REPO:$IMAGE $ECR_REGISTRY/ECR_REPO:$IMAGE 
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE

      - name: Configure kubectl 
        run: |
          aws eks update-kubeconfig --name author-service --region eu-north-1 

      - name: Update Kubernetes Deployment
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
          ECR_REPO: author-service
        run: |
          kubectl set image deployment/author-service author-service=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG -n author-service
          kubectl rollout status deployment/author-service -n author service
          kubectl get pods -n author service         


